-- Generated from generator/demo_specs/aws-thailand-food-cold-chain.json
-- Regenerate with: python3 generator/gen_repo_docs.py aws-thailand-food-cold-chain
-- This is the schema that is actually deployed for THAILAND_FOOD_COLD_CHAIN.

-- Alerts fire on the bottom tail of Cold Chain Compliance
-- (lower is worse for this metric).
CREATE OR REPLACE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH thresh AS (
  SELECT PERCENTILE_CONT(0.09) WITHIN GROUP (ORDER BY KPI_COLD_CHAIN_COMPLIANCE) AS T
  FROM RAW.TEMPERATURE_READINGS
)
SELECT
  e.ID AS ENTITY_ID,
  e.NAME AS ENTITY_NAME,
  e.REGION,
  e.CATEGORY,
  e.STATUS,
  COUNT(*) AS EVENT_COUNT,
  SUM(CASE WHEN f.KPI_COLD_CHAIN_COMPLIANCE <= (SELECT T FROM thresh) THEN 1 ELSE 0 END) AS ALERT_COUNT,
  ROUND(AVG(f.KPI_COLD_CHAIN_COMPLIANCE), 2) AS AVG_COLD_CHAIN_COMPLIANCE,
  ROUND(AVG(f.KPI_AVG_TRANSIT_TEMP), 2) AS AVG_TRANSIT_TEMP,
  ROUND(AVG(f.KPI_ON_TIME_DELIVERY), 2) AS AVG_ON_TIME_DELIVERY
FROM RAW.TEMPERATURE_READINGS f
JOIN RAW.THAI_FOOD_LOGISTICS e ON e.ID = f.ENTITY_ID
CROSS JOIN thresh
GROUP BY e.ID, e.NAME, e.REGION, e.CATEGORY, e.STATUS;

CREATE OR REPLACE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT
  f.EVENT_DATE AS METRIC_DATE,
  COUNT(*) AS EVENT_COUNT,
  ROUND(AVG(f.KPI_COLD_CHAIN_COMPLIANCE), 2) AS AVG_COLD_CHAIN_COMPLIANCE,
  ROUND(AVG(f.KPI_AVG_TRANSIT_TEMP), 2) AS AVG_TRANSIT_TEMP,
  ROUND(AVG(f.KPI_ON_TIME_DELIVERY), 2) AS AVG_ON_TIME_DELIVERY
FROM RAW.TEMPERATURE_READINGS f
GROUP BY f.EVENT_DATE;

-- DISPLAY is rendered here so it is byte-identical to the card the app
-- was designed with (asserted by the round-trip check in kpi_parse.py).
CREATE OR REPLACE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS WITH ev AS (SELECT AVG(KPI_COLD_CHAIN_COMPLIANCE) AS KPI_COLD_CHAIN_COMPLIANCE, AVG(KPI_AVG_TRANSIT_TEMP) AS KPI_AVG_TRANSIT_TEMP, AVG(KPI_ON_TIME_DELIVERY) AS KPI_ON_TIME_DELIVERY FROM RAW.TEMPERATURE_READINGS),
     en AS (SELECT SUM(KPI_PRODUCT_LOSS_QTD) AS KPI_PRODUCT_LOSS_QTD, SUM(KPI_PREDICTED_FAILURES_7D) AS KPI_PREDICTED_FAILURES_7D, SUM(KPI_ACTIVE_SHIPMENTS) AS KPI_ACTIVE_SHIPMENTS, SUM(KPI_DOOR_OPEN_EVENTS_TODAY) AS KPI_DOOR_OPEN_EVENTS_TODAY FROM RAW.THAI_FOOD_LOGISTICS)
  SELECT 1 AS SORT_ORDER, 'Cold Chain Compliance' AS TITLE, KPI_COLD_CHAIN_COMPLIANCE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_COLD_CHAIN_COMPLIANCE), 1) AS DECIMAL(38,1))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 2 AS SORT_ORDER, 'Product Loss (QTD)' AS TITLE, KPI_PRODUCT_LOSS_QTD AS VALUE_NUM, '฿' || TO_VARCHAR(CAST(ROUND(((KPI_PRODUCT_LOSS_QTD) / 1000000)) AS DECIMAL(38,0))) || 'M' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 3 AS SORT_ORDER, 'Predicted Failures (7d)' AS TITLE, KPI_PREDICTED_FAILURES_7D AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_PREDICTED_FAILURES_7D)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 4 AS SORT_ORDER, 'Active Shipments' AS TITLE, KPI_ACTIVE_SHIPMENTS AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_ACTIVE_SHIPMENTS)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 5 AS SORT_ORDER, 'Avg Transit Temp' AS TITLE, KPI_AVG_TRANSIT_TEMP AS VALUE_NUM, '-' || TO_VARCHAR(CAST(ROUND((KPI_AVG_TRANSIT_TEMP), 1) AS DECIMAL(38,1))) || '°C' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 6 AS SORT_ORDER, 'Door-Open Events Today' AS TITLE, KPI_DOOR_OPEN_EVENTS_TODAY AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_DOOR_OPEN_EVENTS_TODAY)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 7 AS SORT_ORDER, 'On-Time Delivery' AS TITLE, KPI_ON_TIME_DELIVERY AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_ON_TIME_DELIVERY), 1) AS DECIMAL(38,1))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
