-- ============================================================================
-- 06_ML_MODELS.SQL — ML Functions for Cold Chain Monitoring
-- ============================================================================
USE DATABASE COLD_CHAIN;
USE SCHEMA ML;

-- ML.FORECAST: EXCURSION_FORECAST_MODEL
CREATE OR REPLACE SNOWFLAKE.ML.FORECAST ML.EXCURSION_FORECAST_MODEL(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.EXCURSION_TIMESERIES'),
  SERIES_COLNAME => 'ASSET_ID',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y'
  
);

CREATE OR REPLACE TABLE ML.EXCURSION_FORECAST_MODEL_RESULTS AS
SELECT * FROM TABLE(ML.EXCURSION_FORECAST_MODEL!FORECAST(FORECASTING_PERIODS => 14));

-- ML.ANOMALY_DETECTION: TEMP_ANOMALY_MODEL
CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION ML.TEMP_ANOMALY_MODEL(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.EXCURSION_TIMESERIES'),
  SERIES_COLNAME => 'ASSET_ID',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y',
  LABEL_COLNAME => ''
);

CREATE OR REPLACE TABLE ML.TEMP_ANOMALY_MODEL_RESULTS AS
SELECT * FROM TABLE(ML.TEMP_ANOMALY_MODEL!DETECT_ANOMALIES(INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.EXCURSION_TIMESERIES'), SERIES_COLNAME => 'ASSET_ID', TIMESTAMP_COLNAME => 'DS', TARGET_COLNAME => 'Y'));

