-- ============================================================================
-- 99_RESET.SQL — Reset Cold Chain Monitoring to clean demo state
-- ============================================================================
USE DATABASE COLD_CHAIN;

-- Suspend tasks during demo
ALTER TASK IF EXISTS APP.TASK_INGEST_TELEMETRY SUSPEND;
ALTER TASK IF EXISTS APP.TASK_DETECT_ANOMALIES SUSPEND;
ALTER TASK IF EXISTS APP.TASK_SEND_ALERTS SUSPEND;

-- Force refresh Dynamic Tables
ALTER DYNAMIC TABLE CURATED.FLEET_COMPLIANCE_STATUS REFRESH;
ALTER DYNAMIC TABLE CURATED.EXCURSION_TIMESERIES REFRESH;
ALTER DYNAMIC TABLE CURATED.ROUTE_RISK_SCORES REFRESH;
ALTER DYNAMIC TABLE CURATED.PRODUCT_LOSS_SUMMARY REFRESH;

-- Verify key demo numbers
-- SELECT COUNT(*) FROM COLD_CHAIN.RAW.TEMPERATURE_READINGS → 2000000
-- SELECT COUNT(*) FROM COLD_CHAIN.RAW.EXCURSION_EVENTS → 1200
-- SELECT COUNT(*) FROM COLD_CHAIN.CURATED.FLEET_COMPLIANCE_STATUS WHERE STATUS = 'NON_COMPLIANT' → ~47

-- Resume tasks
ALTER TASK IF EXISTS APP.TASK_SEND_ALERTS RESUME;
ALTER TASK IF EXISTS APP.TASK_DETECT_ANOMALIES RESUME;
ALTER TASK IF EXISTS APP.TASK_INGEST_TELEMETRY RESUME;
